nodeLinker: node-modules

npmMinimalAgeGate: 2880

npmPreapprovedPackages:
  - '@navikt/*'
  - 'react@19.2.1'
  - 'react-dom@19.2.1'
  - 'next@16.0.7'
  - 'eslint-config-next@16.0.7'
  - '@next/eslint-plugin-next@16.0.7'
  - '@next/env@16.0.7'
  - '@next/swc-darwin-x64@16.0.7'
  - '@next/swc-darwin-arm64@16.0.7'
  - '@next/swc-darwin-x64@16.0.7'
  - '@next/swc-linux-arm64-gnu@16.0.7'
  - '@next/swc-linux-arm64-musl@16.0.7'
  - '@next/swc-linux-x64-gnu@16.0.7'
  - '@next/swc-linux-x64-musl@16.0.7'
  - '@next/swc-win32-arm64-msvc@16.0.7'
  - '@next/swc-win32-x64-msvc@16.0.7'

npmScopes:
  navikt:
    npmAlwaysAuth: true
    npmAuthToken: '${NPM_AUTH_TOKEN:-}'
    npmRegistryServer: 'https://npm.pkg.github.com'

plugins:
  - checksum: e5e6e2885ab0e6521b70b0af7c6d8ca2c75dcae2403706fc4600a783b339a6530a476dafb9450c9436ca4050eb6bdee9b62e6e2cebfecf1e81dd709a2480dc07
    path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: 'https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js'

yarnPath: .yarn/releases/yarn-4.12.0.cjs
