apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: helsesjekk-bot
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - 'https://helsesjekk-bot.intern.nav.no'
    - 'https://helsesjekk-bot.nav.no'
  replicas:
    min: 2
    max: 3
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
  leaderElection: true
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: helsesjekk-bot
        tier: db-f1-micro
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
    sidecar:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: slack.com
        - host: api.slack.com
        - host: wss-primary.slack.com
  liveness:
    path: /api/internal/is_alive
    initialDelay: 10
  readiness:
    path: /api/internal/is_ready
    initialDelay: 10
  envFrom:
    - secret: helsesjekk-bot-secrets
