apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: helsesjekk-bot
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{image}}
  port: 5000
  ingresses:
    - 'https://helsesjekk-bot.intern.nav.no'
  replicas:
    min: 1
    max: 2
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 5m
      memory: 256Mi
  leaderElection: true
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: helsesjekk-bot
  accessPolicy:
    outbound:
      external:
        - host: slack.com
        - host: api.slack.com
        - host: wss-primary.slack.com
  liveness:
    path: /internal/is_alive
    initialDelay: 10
  readiness:
    path: /internal/is_ready
    initialDelay: 10
  envFrom:
    - secret: helsesjekk-bot-secrets
