apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: helsesjekk-bot
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - 'https://helsesjekk-bot.intern.dev.nav.no'
  replicas:
    min: 1
    max: 2
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 5m
      memory: 256Mi
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
  leaderElection: true
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: helsesjekk-bot
        tier: db-f1-micro
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: true
      claims:
        extra:
          - 'NAVident'
    sidecar:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: slack.com
        - host: api.slack.com
        - host: wss-primary.slack.com
  liveness:
    path: /api/internal/is_alive
    initialDelay: 10
  readiness:
    path: /api/internal/is_ready
    initialDelay: 10
  envFrom:
    - secret: helsesjekk-bot-secrets
